### ISSUE TITLE
Implement Server

### ISSUE THREAD

**Issue by juan-medina** [ev3dev-lang-java/bridge#2]
Create the server based on system test

- [x] Implement PUT /subscribe/
- [x] Implement  GET /subscribe/{subscriber}/
- [x] Implement  DELETE /subscribe/{subscriber}/
- [x] Implement  PUT /publish/{topic}/
- [x] Implement  GET /messages/{subscriber}/

**Comment by juan-medina** [comment]
http://www.baeldung.com/java-in-memory-databases

**Comment by jabrena** [comment]
Maybe we could define the model to store the messages.

**Comment by juan-medina** [comment]
we are not going to define a model in the standard way of think in data, so no SQL no tables, we are going fulling JPA on this.

So they will be classes and relations between them.

**Comment by jabrena** [comment]
Totally agree

**Comment by juan-medina** [comment]
two done 💃

**Comment by juan-medina** [comment]
http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-property-expressions

**Comment by juan-medina** [comment]
minor details to complete the issue

**Comment by juan-medina** [comment]
feature complete

bridge available in:

https://brick-bridge.herokuapp.com/

**Comment by jabrena** [comment]
I will test the API
